Question 2 By Borna Maherani ID = 401243079

<h1> Geting input </h1>

In [2]:
import numpy as np

m = int (input("Enter the number of rows: "))
n = int (input("Enter the number of columns: "))

A = np.empty((0,n), float)
"""
geting the matrix
example: n=4 m=3 
1 3 4 3
0 4 9 5
10 4 1 6
"""

for i in range(0,m):
    line = input(f"Enter row {i+1}: ").split()
    line = list(map(int, line))
    A = np.append(A, np.array([line]), axis=0)  
print(A)


[[ 1.  3.  4.  3.]
 [ 0.  4.  9.  5.]
 [10.  4.  1.  6.]]


<h1>echelon form convertor</h1>

In [44]:
def rref(A,n,m):
    result = np.copy(A)
    for i in range(0, m):
        j = 0
        print (result) # for showing its step in reducing rows
        # finding first non zero element in a row
        while (j < n and result[i][j] == 0): 
            j += 1
        # if  a row is all zero countinue to the next row
        if j == n:
            continue
        # convert the first non zero element in a row into 1
        result[i] = result[i] / result[i][j]
        # Reducing all rows from pivot
        for k in range(0,m):
            if k == i: 
                continue
            else:
                result[k] -= result[k][j]*result[i]
            print(result)
    return result
# A = np.array([
#     [4.,6.,8.],
#     [3.,7.,7.],
#     [6.,14.,15.],
#     [1.,3.,3.]
# ])
# n = 3 
# m = 4
Z = rref(A,n,m)

[[ 1.  3.  4.  3.]
 [ 0.  4.  9.  5.]
 [10.  4.  1.  6.]]
[[ 1.  3.  4.  3.]
 [ 0.  4.  9.  5.]
 [10.  4.  1.  6.]]
[[  1.   3.   4.   3.]
 [  0.   4.   9.   5.]
 [  0. -26. -39. -24.]]
[[  1.   3.   4.   3.]
 [  0.   4.   9.   5.]
 [  0. -26. -39. -24.]]
[[  1.     0.    -2.75  -0.75]
 [  0.     1.     2.25   1.25]
 [  0.   -26.   -39.   -24.  ]]
[[ 1.    0.   -2.75 -0.75]
 [ 0.    1.    2.25  1.25]
 [ 0.    0.   19.5   8.5 ]]
[[ 1.    0.   -2.75 -0.75]
 [ 0.    1.    2.25  1.25]
 [ 0.    0.   19.5   8.5 ]]
[[1.         0.         0.         0.44871795]
 [0.         1.         2.25       1.25      ]
 [0.         0.         1.         0.43589744]]
[[1.         0.         0.         0.44871795]
 [0.         1.         0.         0.26923077]
 [0.         0.         1.         0.43589744]]


<h1> Finding Rank from echelon form </h1>

In [45]:
# Rank of a matrix is number of pivot columns of its echelon form
def pivotCols(echelon_A, n, m):
    rank = 0
    pvCol=[]
    for j in range(0, n):
        flag = 0
        for i in range(0, m):
            if echelon_A[i][j] == 0 or echelon_A[i][j] == -0:
                continue
            elif echelon_A[i][j] == 1 and i not in pvCol:
                flag += 1
                pvCol.append(i)
            else:
                break
        if flag == 1:
            rank += 1
        if rank >= m:
            return rank
    return rank
pivotCols(Z, n, m)

3

<h1>TestCases</h1>

In [43]:
Z = np.array([
    [-6.,1.,-2.],
    [28.,-12.,20.],
    [22.,-11.,18.]
])
Z = rref(Z,3,3)
print(Z)
print(pivotCols(Z,3,3))
print(np.linalg.matrix_rank(Z))


Z = np.array([
    [-6.,1.,-2.,5.,5.],
    [28.,-12.,20.,6.,6.],
    [22.,-11.,18.,7.,7.]
])
Z = rref(Z,5,3)
print(Z)
print(pivotCols(Z,5,3))
print(np.linalg.matrix_rank(Z))


Z = np.array([
    [1.,0.,2.,3.],
    [0.,1.,4.,5.],
    [0.,3.,12.,15.]
])
Z = rref(Z,4,3)
print(Z)
print(pivotCols(Z,4,3))
print(np.linalg.matrix_rank(Z))

Z = np.array([
    [1.,0.,2.,3.,11.],
    [0.,1.,4.,5.,7.],
    [0.,3.,12.,15.,6.],
    [1.,6.,8.,0.,12.]
])
Z = rref(Z,5,4)
print(Z)
print(pivotCols(Z,5,4))
print(np.linalg.matrix_rank(Z))




[[ -6.   1.  -2.]
 [ 28. -12.  20.]
 [ 22. -11.  18.]]
[[  1.          -0.16666667   0.33333333]
 [  0.          -7.33333333  10.66666667]
 [ 22.         -11.          18.        ]]
[[ 1.         -0.16666667  0.33333333]
 [ 0.         -7.33333333 10.66666667]
 [ 0.         -7.33333333 10.66666667]]
[[ 1.         -0.16666667  0.33333333]
 [ 0.         -7.33333333 10.66666667]
 [ 0.         -7.33333333 10.66666667]]
[[ 1.          0.          0.09090909]
 [-0.          1.         -1.45454545]
 [ 0.         -7.33333333 10.66666667]]
[[ 1.          0.          0.09090909]
 [-0.          1.         -1.45454545]
 [ 0.          0.          0.        ]]
[[ 1.          0.          0.09090909]
 [-0.          1.         -1.45454545]
 [ 0.          0.          0.        ]]
[[ 1.          0.          0.09090909]
 [-0.          1.         -1.45454545]
 [ 0.          0.          0.        ]]
2
2
[[ -6.   1.  -2.   5.   5.]
 [ 28. -12.  20.   6.   6.]
 [ 22. -11.  18.   7.   7.]]
[[  1.          -0.16